### ISSUE TITLE
not complete

### ISSUE THREAD

**Issue by heleicn-gz** [iwat/talib-cdl-go#2]
Your talib-cdl-go library is not complete. Will it be updated?

**Comment by iwat** [comment]
I'm afraid not, I no longer need it so it won't be updated. However, its code architecture (which follows the original implementation is good enough to be extended.

Feel free to fork, PRs are welcomed.

**Comment by nifflin** [comment]
why not continue? have you migrated to the original python version?

**Comment by iwat** [comment]
No. I just lose interest in candle pattern analysis. Anyway, all ported patterns have high effectiveness according to a reference website.

**Comment by nifflin** [comment]
Do you have new research direction to accomplish the same thing?

**Comment by iwat** [comment]
No. I just stopped doing it. I would love to invest more time on deep learning (although I’ve never started it).

**Comment by nifflin** [comment]
It seems deep learning is the trend of quant. I think you are right, CDL is too old.
